Opening ../test/input.cion ...

Initializing error handler ...
sizeof(std::string) = 8
Initializing lexer ...
Initializing lexer filter ...
Initializing parser ...

Parsing ../test/input.cion ...
	time required = 1.83333 ms

Printing generated AST ...

	time required to print AST = 4.463 ms
