#ifndef CION_AST_ALL_HEADER
#define CION_AST_ALL_HEADER

#include "cion/ast/binary_assign_expr.hpp"
#include "cion/ast/binary_expr.hpp"
#include "cion/ast/boolean_expr.hpp"
#include "cion/ast/break_stmnt.hpp"
#include "cion/ast/call_expr.hpp"
#include "cion/ast/char_expr.hpp"
#include "cion/ast/compilation_unit_decl.hpp"
#include "cion/ast/compound_stmnt.hpp"
#include "cion/ast/conditional_expr.hpp"
#include "cion/ast/continue_stmnt.hpp"
#include "cion/ast/empty_stmnt.hpp"
#include "cion/ast/expr.hpp"
#include "cion/ast/expr_stmnt.hpp"
#include "cion/ast/decl_stmnt.hpp"
#include "cion/ast/float_expr.hpp"
#include "cion/ast/function_decl.hpp"
#include "cion/ast/if_stmnt.hpp"
#include "cion/ast/index_expr.hpp"
#include "cion/ast/integer_expr.hpp"
#include "cion/ast/param_decl.hpp"
#include "cion/ast/nothing_expr.hpp"
#include "cion/ast/nothing_type.hpp"
#include "cion/ast/builtin_type.hpp"
#include "cion/ast/return_stmnt.hpp"
#include "cion/ast/stmnt.hpp"
#include "cion/ast/string_expr.hpp"
#include "cion/ast/type.hpp"
#include "cion/ast/unary_expr.hpp"
#include "cion/ast/var_decl.hpp"
#include "cion/ast/var_expr.hpp"
#include "cion/ast/while_stmnt.hpp"

#endif // CION_AST_ALL_HEADER
